### ISSUE TITLE
Bad links in page

### ISSUE THREAD

**Issue by vstebunov** [compiiile/compiiile#1]
Hi, I try your application and it's very good!

Search and generation is very well.

But I find bug.

I don't know your business, but send you for your knowing.

On dev mode, when I create page with link i got:

`
http://localhost:3000/#/c/home/r4ge/.config/yarn/global/node_modules/compiiile/202112262304-percentd0percentbcpercentd0percentb8percentd0percentbapercentd1percent81-percentd1percent8fpercentd0percentbfpercentd0percentbepercentd0percentbdpercentd1percent81percentd0percentbapercentd0percentb8percentd0percentb9-percentd1percent84percentd0percentb0percentd0percentbdpercentd0percentba
`

But actually right link is

`
http://localhost:3000/#/c/202112262304-miks-yaponskij-fank
`

Best regards and lucky for you.

VS

**Comment by AlbanCrepel** [comment]
Thanks for the bug report. I'll have a look. Can you give me the actual markdown that generated this link ? It is by using a usual link with `[link text](./some-relative-link.md)` ?

**Comment by vstebunov** [comment]
Something like this. It wrote in Russian with utf8.

```
# 202112270900 Собрать DAWless студию

#идея

...

202112270917 Кончились идеи и я переключился на [это](./202112270908-мультимедия-компания.md)

202112270920 Еще это связано с [японским фанк миксом](./202112262304-микс-японский-фанк.md) и [супер сэмплером](./202112262213-супер-сэмплер.md)
```

I understand, maybe you change name of file, but not change name of link.

**Comment by AlbanCrepel** [comment]
Ok I'll have a look. To be honest, I didn't test with Russian with utf8.

**Comment by vstebunov** [comment]
It's ok.
As I think problem with non-latin-based languages.
Thank you, for you response.

**Comment by AlbanCrepel** [comment]
Exactly. I had a look, and both [DM Sans](https://fonts.google.com/specimen/DM+Sans/tester) and [Archivo](https://fonts.google.com/specimen/Archivo/tester?query=archivo) are used to display markdown (hosted locally, not using Google's CDN), but I am really sorry it seems that these fonts don't support cyrillic characters. That's why you have all these percent-prefixed characters in the url.

If you have any idea on how to fix this, feel free to work on a fix. For the time being, I'll let this issue opened and see if an alternative is possible for non-latin-based languages.

Edit: It seems to come from the way we load the file, we currently use `fs.readFileSync(filePath, {encoding: 'utf8'})` and this doesn't handle non-utf-8 characters. [iconv-lite](https://www.npmjs.com/package/iconv-lite) seems to solve the problem.

Edit2: I just decoded paths and it's now working

**Comment by AlbanCrepel** [comment]
@vstebunov I fixed it in 1.0.9 🎉

**Comment by vstebunov** [comment]
Great!
Sorry to say it. 
But now I start server and all crushed:
`URI malformed

    at decodeURI (<anonymous>)
    at resolveFileFromRelativePath (/home/r4ge/.config/yarn/global/node_modules/compiiile/bin/client/vite.config.js:95:11)
    at Object.md.renderer.rules.link_open (/home/r4ge/.config/yarn/global/node_modules/compiiile/bin/client/vite.config.js:105:14)
    at Renderer.renderInline (/home/r4ge/.config/yarn/global/node_modules/markdown-it/lib/renderer.js:275:28)
    at Renderer.render (/home/r4ge/.config/yarn/global/node_modules/markdown-it/lib/renderer.js:330:22)
    at MarkdownIt.render (/home/r4ge/.config/yarn/global/node_modules/markdown-it/lib/index.js:544:24)
    at /home/r4ge/.config/yarn/global/node_modules/compiiile/bin/client/vite.config.js:221:57
    at Array.forEach (<anonymous>)
    at Context_default.scanDirectoryRecursively (/home/r4ge/.config/yarn/global/node_modules/compiiile/bin/client/vite.config.js:200:73)
    at new Context_default (/home/r4ge/.config/yarn/global/node_modules/compiiile/bin/client/vite.config.j
`

**Comment by AlbanCrepel** [comment]
@vstebunov How about now in 1.0.11 ? An encoding has been added before decoding the uri.

**Comment by vstebunov** [comment]
@AlbanCrepel  
Great you so fast at response and fix!

Work well, but some links get addition

From page http://localhost:3000/#/c/202109261228-hellblade-senuas-sacrifice got this in link

```
http://localhost:3000/#/c/home/r4ge/.config/yarn/global/node_modules/compiiile/202109251732-journey
```

**Comment by AlbanCrepel** [comment]
Thank you for taking the time to report bugs. Can you once again provide the exact markdown tag used ? Like `[link text](./some-relative-link.md)` and the file name that it points to. This will help find the source of the issue.

**Comment by vstebunov** [comment]
I get out from PC and couldn't send link now, but it same as first links, i
use rule yyyymmdd-theme scheme. All like this:

./link.md

UPD: 

in Markdown
```

В игре очень красивая графика, северные леса, и куча всяких линзовых эффектов. Благодаря наушникам всё шепчет и шлёпает очень круто. Сама по себе игра мне почему-то больше напоминает [Journey](./202109251732-journey.md) и [Life is Strange](./202104221028-life-is-strange.md). 

```

**Comment by vstebunov** [comment]
Sorry, for your bother.

*UPD* add quick fix https://github.com/AlbanCrepel/compiiile/pull/2 for view


I found out main problem with non-latin encoding. 

It is line 62 in markdown.js

We have in ```file.path``` variable this line
```
/home/r4ge/PARA/1_projects/compiiile/202105212218-%25D0%25B4%25D0%25B7%25D0%25B5%25D0%25BD-%25D0%25B1%25D1%2583%25D0%25B4%25D0%25B4%25D0%25B8%25D0%25B7%25D0%25BC.md 
```
It's looks like double encoded uri line, cause if we do this:
```
const decodedFilePath = decodeURIComponent(decodeURIComponent(file.path));
```

We got normal non latin string
```
/home/r4ge/PARA/1_projects/compiiile/202105212218-дзен-буддизм.md
```

**Comment by AlbanCrepel** [comment]
Thanks for your PR, can you confirm everything works well for you in 1.0.12 ?

**Comment by vstebunov** [comment]
Yes, It's works well!

Thank you.
