### ISSUE TITLE
Favicon doesn't displayed

### ISSUE THREAD

**Issue by WilliamBurillon** [compiiile/compiiile#14]
Compiiile version : the laste available 
Compiiile config js : 
```
module.exports = {
    title: "MBA1 Développeur Full Stack - Docker",
    logo: "./Logomds.jpeg",
    dest: "my-custom-build-folder",
}
```

issue : 

The logo isn't rendered on the page. The request made is `http://favicon.png/` and it could be the root cause in my opinion. 
If I go to the url http://localhost:4321/favicon.png, I have the logo. 

Tell me if you need more info sire !

**Comment by AlbanCrepel** [comment]
Hey @WilliamBurillon , I've just fixed that in the last version that I published (2.1.3), thanks for reporting this issue 💯
