### ISSUE TITLE
Error related to missing vue when building for production

### ISSUE THREAD

**Issue by Akhu** [compiiile/compiiile#18]
Hi, 

I have installed compiiile as global, and if i run it with `dev` it's working fine, but I get this error when I run `compiiile build` : 

```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vue' imported from /Users/me/Code/Text/Formations/Swift/.compiiile/dist/renderers.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:890:9)
    at moduleResolve (node:internal/modules/esm/resolve:939:20)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.18.2
```

I tried to install vue globally but nothing changes 🫠

Thanks for the help !

**Comment by AlbanCrepel** [comment]
Hi @Akhu, it seems to be treating `vue` as a dev dependency, although it is included in the project's dependencies. I began to investigate without finding a sustainable solution. Fo the moment, you can install compiiile locally (and not globally ; with the dependency manager that you want) and the `build` command should work.

**Comment by Akhu** [comment]
It's seems to be related to my environment, because in VS Code terminal I get the error, but when using native MacOS terminal everything is working well... Both are on node v18 although :/

**Comment by AlbanCrepel** [comment]
It could be related to the `bin` directory of your dependency manager not added to your `PATH` (and loading the `PATH` variable could have a different behaviour depending on the terminal you are using). Here is how people have done it for `npm` and `yarn`:
- npm : https://bobbyhadz.com/blog/not-recognized-as-internal-or-external-command-vue-cli-service#update-the-path-on-macos-or-linux
- yarn : https://stackoverflow.com/a/40333409

**Comment by Akhu** [comment]
So even installing locally it fails to build. 

I had installed the latest Compiiile version (it use Astro now, it was'nt before didn't it ?)

```
Error: ENOENT: no such file or directory, lstat '/Formations/Swift/Swift%20M2/node_modules/compiiile/.compiiile/public'
12:53:14 [astro] Missing pages directory: src/pages
Error: Cannot find package.json from /Formations/Swift/Swift%20M2/node_modules/compiiile/.compiiile/
```

Here is my setup so far :
![Capture d’écran 2023-11-18 à 12 55 52](https://github.com/AlbanCrepel/compiiile/assets/2813962/7939380f-7e4a-47fa-aa7c-273ed2e6b3c7)

My package.json
```json
{
  "dependencies": {
    "compiiile": "^2.1.5"
  },
  "scripts": {
    "dev": "compiiile dev",
    "build": "compiiile build",
    "preview": "compiiile preview"
  }

}
```

My compiiile settings 
```js
module.exports = {
    title: "UIKit & SwiftUI Débutant",
    logo: "./favicon.png",
    favicon: "./favicon.png"
}
```
Thanks for the help, I don't really understand why it fail ¯\_(ツ)_/¯

**Comment by AlbanCrepel** [comment]
From my understanding, the file structure from the screenshot doesn't seem right: the `node_modules` folder isn't located in the same directory as your `package.json`. Also, the config file should not use a CommonJS syntax anymore, but an ESM syntax, as explained in the [changelog](https://compiiile.me/c/changelog).

You could try having this project structure:

```
|-- package.json
|-- node_modules
|-- compiiile.config.js
|-- README.md
|-- favicon.png
|-- Swift M2
    |-- README.md
```

Your settings file could have this content (the `favicon` key is not necessary):

```js
export default {
    title: "UIKit & SwiftUI Débutant",
    logo: "./favicon.png"
}
```

The built files in the `.compiiile` folder should be placed at your project's root directory. I hope these settings will suit your project.

If the goal was to have multiple compiiile instances in your folder, tell me and I can help with another directory example for your use case.

EDIT: Yes, the v2 version now uses Astro.

**Comment by AlbanCrepel** [comment]
As seen with @Akhu, it was a problem related to the root folder name containing a space, and thus an internal library could not resolve the `package.json` file. After renaming the file, the project was working. I can now close this issue.

**Comment by mikestreety** [comment]
Sorry to re-open this issue, but I am facing the same when building globally.

I'm trying to build compiiile into a docker image (separate topic to be discussed at a later date) to no avail.

This error I get is the following - seems to only happen when installed globally (`npm install -g @compiiile/compiiile@2.7.0`)

```node
node:internal/modules/esm/resolve:844
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vue' imported from /app/.compiiile/dist/renderers.mjs
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

This is the dockerfile I'm using

```Dockerfile
FROM node:21.6-alpine3.19

RUN npm install -g @compiiile/compiiile@2.7.0

RUN mkdir /app
WORKDIR /app

CMD [ "/usr/local/bin/compiiile", "build" ]
```

With the following command to render it:

```bash
docker run -it -v $(pwd):/app compiiile "/bin/sh" #connect to the image
compiiile build
```

However, if I install locally once the Docker image is booted up (`npm install @compiiile/compiiile@2.7.0`) and build locally (`./node_modules/.bin/compiiile build`) it works fine.

**Comment by AlbanCrepel** [comment]
@mikestreety The scope of this issue is way out of bounds of just the Compiiile project, it is due to [this from the node documentation](https://nodejs.org/api/esm.html#esm_no_node_path):

> `NODE_PATH` is not part of resolving `import` specifiers. Please use symlinks if this behavior is desired.

Here, the `vue` package is not resolved from the globally-installed Compiiile package. I am still investigating (the solution would be to rewrite the cli to use the commonJS syntax), but for the time being, the best solution is to install Compiiile locally instead of globally if you want to build the project.

Sorry for this, I hope to resolve it soon.

**Comment by mikestreety** [comment]
Please don't be sorry at all! I'll do some more digging and see if I can come up with anything my end.

**Comment by AlbanCrepel** [comment]
@mikestreety Installing Compiiile globally with npm should now work using `2.7.4` :tada:

The build command now works after running `npm install -g @compiiile/compiiile` or `yarn global add @compiiile/compiiile`.
A local installation is not needed anymore to get the build command to work.

I also added a `Dockerfile` at the project root with the corresponding documentation on how to use it : https://github.com/compiiile/compiiile?tab=readme-ov-file#using-docker

**Comment by mikestreety** [comment]
@AlbanCrepel you are on fire! 🔥
