### ISSUE TITLE
Not an Issue 🔧 Compiiile + Github Actions + CloudFlare Pages 

### ISSUE THREAD

**Issue by Akhu** [compiiile/compiiile#21]
Here is a quick configuration for people who wants to use Compiiile with **Github Actions and Cloudflare Pages** for multiple websites deployments from a single repository.

Here it is on Github Marketplace : https://github.com/marketplace/actions/compiiile-cloudflare-pages 

Enjoy 💡

**Comment by AlbanCrepel** [comment]
Hey @Akhu, thanks for your GitHub Action, it will be very helpful ! I am thinking of adding this kind of Compiiile-related content in some showcase section (maybe in the README or in a dedicated page ? Idk yet).

**Comment by AlbanCrepel** [comment]
Hey @Akhu, I added your project to the project's README in a new section: [community projects](https://github.com/compiiile/compiiile?tab=readme-ov-file#community-projects). Thanks again :sparkles:.
