### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by mikestreety** [compiiile/compiiile#27]
Hey, thanks so much for this - I think it is going to save me a world of pain!

Is there anyway to make the light theme default (or add a theme switcher). I struggle with dark themes and it is the only thing holding me back from using this.

Thanks again!

**Comment by AlbanCrepel** [comment]
Hey @mikestreety, thanks for your feedback. This feature is a work in progress, it should be added really soon ! :sparkles:

**Comment by AlbanCrepel** [comment]
@mikestreety This feature is now added to the `2.5.0` version, enjoy :fire:
