### ISSUE TITLE
Use first heading/h1 for navigation title

### ISSUE THREAD

**Issue by mikestreety** [compiiile/compiiile#32]
Off the back of my [premature PR](https://github.com/compiiile/compiiile/pull/29), I wonder if you would be open to the possibility of this being a configuration option?

As a bit of background:

We maintain over 60 websites - more and more of them have a `docs` folder detailing parts of the application. I was looking for a Docusaurus-style framework I could throw a folder of markdown files at and it generate a navigation and render the markdown, which this is absolutely perfect for. 

I plan to integrate this into our CI pipeline - building and uploading the rendered content to static host - a 0-config-markdown rendering-library-framework thing.  (Thank you, by the way).

To avoid repeating the `h1` inside the front-matter, I was wondering if you would be open to adding a [config option](https://github.com/compiiile/compiiile?tab=readme-ov-file#custom-configuration)? 

I was thinking something like `useHeadingForNaviationTitle` or similar, which would take the first h1 (or first h2, if h1 is missing etc) and use that for the sidebar navigation title (much like  Docusaurus does) unless a `title:` is specified in the front-matter?

Thanks

**Comment by AlbanCrepel** [comment]
@mikestreety This feature is now added to the `2.7.0` version, enjoy :fire:

**Comment by mikestreety** [comment]
Incredible, thank you!
