### ISSUE TITLE
Images not resolving when using `build`

### ISSUE THREAD

**Issue by Akhu** [compiiile/compiiile#4]
Maybe I am missing something, but the `build` command does not copy images into `dist` folder

Here is my file structure : 

Root Folder
-> Folder
--> `images` folder
--> multiples .md files referencing images with `![](images/myImage.jpg)`

Then in my `dist` folder generated using `compiiile build` images are not present and not resolved.

I can fix this by manually moving my images inside an `dist/images` folder.

Thanks for your help :)

**Comment by AlbanCrepel** [comment]
Hey @Akhu , you can try by referencing images with their relative paths, like so : `![](./images/myImage.jpg)` in `Folder/test.md`. Tell me if this worked for you :)

**Comment by Akhu** [comment]
That was the issue, it's working well now :) Thanks ! ⚡️

**Comment by michael-ames** [comment]
Hi — I'm referencing images in my markdown using the relative paths recommended here, but I seem to be running into a vite permissions issue:
**The request url ".../test-compiiile/images/imagename.jpg" is outside of Vite serving allow list.**

This seems to happen whether I have the image files in my compiiile root folder or in an /images subfolder. 
Relative links to markdown files work fine, but not image files. 

Not sure if this is something I can fix in compiiile.config.js, or if I need to dig into vite config files, or if there's another easier solution.

**Comment by AlbanCrepel** [comment]
Hi @michael-ames , thanks for reporting this issue that kept lurking 👀 
I fixed it in 1.0.16 🎉 This was indeed a problem from vite fs's configuration.
