### ISSUE TITLE
Weird font behavior

### ISSUE THREAD

**Issue by decima** [compiiile/compiiile#50]
Here is a slide where the font is very weird in term of sizes : 

![image](https://github.com/compiiile/compiiile/assets/1727893/c773bb82-d018-4313-bab2-c3ea1b16f883)

The code of the slide : 

```
    ---

    exemples d'usage : 
    ```html
    <a href="https://perdu.com">Clique sur moi</a>
    ```
    <a href="https://perdu.com">Clique sur moi</a>
    
    ```html
    <a href="https://perdus.com" target="_blank">
        <b>test</b>
    </a>
    ```
    
    <a href="https://perdus.com" target="_blank">
        <b>test</b>
    </a>
    
    
    ```html
    <a href="https://youtu.be/dQw4w9WgXcQ" title="noooooon">
        vidéo importante
    </a>
    ```
    
    <a href="https://youtu.be/dQw4w9WgXcQ" title="noooooon">
        vidéo importante
    </a>
    
    
    ---
```

**Comment by AlbanCrepel** [comment]
@decima This is now fixed using the `2.9.2` version of Compiiile.
