### ISSUE TITLE
HTML table renders with a y-scroll visible

### ISSUE THREAD

**Issue by decima** [compiiile/compiiile#51]
![image](https://github.com/compiiile/compiiile/assets/1727893/429639eb-c280-4019-9d65-dafef9be37d8)
```markdown
    ---
    
    Il y a une hiérarchie logique
    ```html
    <table>
        <tr>
            <th>col 1</th>
            <th>col 2</th>
            <th>col 3</th>
        </tr>
        <tr>
            <td>cell 1</td>
            <td>cell 2</td>
            <td>cell 3</td>
        </tr>
        <tr>
            <td>cell 4</td>
            <td>cell 5</td>
            <td>cell 6</td>
        </tr>
    </table>
    ```
    
    <table>
        <tr>
            <th>col 1</th>
            <th>col 2</th>
            <th>col 3</th>
        </tr>
        <tr>
            <td>cell 1</td>
            <td>cell 2</td>
            <td>cell 3</td>
        </tr>
        <tr>
            <td>cell 4</td>
            <td>cell 5</td>
            <td>cell 6</td>
        </tr>
    </table>
```

**Comment by AlbanCrepel** [comment]
@decima This is now fixed using the `2.9.2` version of Compiiile.
