### ISSUE TITLE
[feature request] ignoring some folders

### ISSUE THREAD

**Issue by decima** [compiiile/compiiile#55]
It would be awesome to being able to add : 
- a global .compiiileignore file which lists what folders to ignore
or
- juste a .compiiileignore in a given folder to make it non liste

(or just something somewhere to prevent from listing, but we could maybe still render it :thinking: )

**Comment by AlbanCrepel** [comment]
For the moment, you can ignore a specific file by setting the `ignore` frontmatter parameter to `true` (as documented under this title in the doc: https://compiiile.me/#write-some-markdown-compiiile-specific-parameters), but a file dedicated to ignore a complete folder with glob patterns is definitely in the roadmap!
