### ISSUE TITLE
Left sidebar doesn't "scroll down" if too long

### ISSUE THREAD

**Issue by wuwwa** [compiiile/compiiile#60]
If the markdown file is too long, the left sidebar doesn't scroll down as you scroll down the text correctly.

**Comment by AlbanCrepel** [comment]
@eotssa Are you talking about the left sidebar (menu with files) or the right sidebar (table of content with titles) ?

**Comment by wuwwa** [comment]
Right side bar, table of contents. Once it reaches the last visible line on my screen, even if I have more text, it doesn't follow until I reach close to the end of the text
