### ISSUE TITLE
Pressing on a markdown file when scrolled down scrolls you back up

### ISSUE THREAD

**Issue by wuwwa** [compiiile/compiiile#62]
Not really a bug since I understand that the page refreshes, but it'd be nice if when I click on a markdown file when scrolled down, I get to retain the sidebar position after the page refreshes

**Comment by AlbanCrepel** [comment]
@eotssa Scrolling up on a new page is intended and follows the behavior that people are used to in 99.9% of websites and knowledge bases. Imagine I click on the link at the bottom of the page to go to the next Markdown page, I would assume that the page would scroll up to see the beginning of the new page. Many people are using this package and I can't comply on every feature request, even more when it's not a behavior we are used to.

**Comment by wuwwa** [comment]
Hey I appreciate what you have here. 

I think the behavior I'm looking for is similar to other documentation sites. Like the tailwind documentation or microsoft learn. 

When I press on a new markdown file (left hand side). The middle should start back at the top, but the left sidebar should maintain its location. 

This is only an issue for people with a lot of files though.

In any case, I really appreciate what you have here. I replaced my other hexos static site with this one!!

**Comment by AlbanCrepel** [comment]
@eotssa Oh sorry, the issue was not quite clear, I see what you mean now ! Yes, since there is a page refresh, the scroll position is not maintained, I'll see what I can do. Thanks for the request, and I'm glad you find Compiiile useful :)

**Comment by AlbanCrepel** [comment]
Hey @eotssa, I've just published a new release of Compiiile (2.15.0), in which the left navbar scrolls to the current active page, which fixes your issue. Enjoy! ✨
